n1 = int(input("enter the number 1 "))
print("first number :",n1)
n2 = int(input("enter the number 2 "))
print("second number :",n2)
n3 = int(input("enter the number 3 "))
print("third number :",n3)
f1 = float(input("enter the float number 1 "))
print("first float number :",f1)
f2 = float(input("enter the float number 1 "))
print("first float number :",f2)
s1 = str(input("enter the string 1 "))
print("first string : ",s1)
s2 = str(input("enter the string 2 "))
print("second string :",s2)
c = complex(input("enter the complex number "))
print("complex number is :",c)
